### ISSUE TITLE
我作为colemak mod dh的一个请求

### ISSUE THREAD

**Issue by Meavel** [pingshunhuangalex/rime-xkjd#3]
我本身也是colemak mod dh的使用者，如果我要换成这个方案，希望能出ios和android版本，不然我不敢换。
（其实我手机还是在使用qwerty配列，一言难尽，用原本方案也同样有些不顺手。）

**Comment by pingshunhuangalex** [comment]
Colemak系列是为十指键盘输入所设计方案，Colemak作者在[Q & A](https://colemak.com/FAQ)中明文不推荐在手机上使用，所以Keydo也没有支持iOS和Android的打算。

从个人的使用体验来看，我的手机和键盘完全是两套分离的肌肉记忆，互不影响（手机一般就是拇指交替输入或者食指滑动输入），手机应该有属于手机自己的键位优化。如果喜欢折腾的话，个人建议不要依样画葫芦想着“统一”或者“照搬”，手机上把元音集中在home row会使误触率大大提高，且会使联想变的困难。
