### ISSUE TITLE
配置文件中的topup_command选项不起作用

### ISSUE THREAD

**Issue by Han-Orz** [pingshunhuangalex/rime-xkjd#4]
在`keydo.schema.yaml`文件中将`tpoup_command`设为`true`，仍无法使用词库中的[avuio]引导的如`小歪	oxcwh`这样的词。

诡异的是，最开始部署`键道·我流`时就把键道6的诗词词库（以i 引导），这个倒是使用正常，但在这个词库后添加新词（i 引导）仍不可用。

**Comment by pingshunhuangalex** [comment]
你好 @Han-Orz 

刚测试了一下，只要词库里有这个编码，`小歪	oxcwh`这样的词条是可以显示的。

因为我流有自己的[选词逻辑](https://github.com/pingshunhuangalex/rime-keydo/blob/main/lua/keydo/processors/select.lua)，不知道是不是你同时安装了官方键道和我的版本引起了一些代码的冲突。

[顶功模块](https://github.com/pingshunhuangalex/rime-keydo/blob/main/lua/for_topup.lua)我暂时没时间重写，所以用的还是和官方版本一样的逻辑，也就是说`topup_command`应该是不受影响的。你可以检查下你的这个诗词词库是否已加载在[词库](https://github.com/pingshunhuangalex/rime-keydo/blob/main/keydo.dict.yaml)里了。因为是形码做引导，你可能需要将词库加载在630词库之前以求稳妥。

需要注意的是，`我流`的设计方向是尽可能利用形码本身的优势和顶功原理，所以你可能也发现`我流`已移除了所有形码做引导的实例，工具类的引导都已切换到`;`了。保留形码引导可能会在后续版本产生未知的冲突。

**Comment by Han-Orz** [comment]
感谢解答，

已确认在重新部署后，部分由[avuio]引导的词库文件并没有加载进入词库中。

关于形码做引导，我目前已经比较习惯于通过这有的方式输入一些如网络俚语、游戏术语、部分花名等，以区别于正常、有意义的词组，这对我来说是个好主意。

再次感谢解答。

**Comment by Han-Orz** [comment]
感谢解答，

已确认在重新部署后，部分由[avuio]引导的词库文件并没有加载进入词库中。

关于形码做引导，我目前已经比较习惯于通过这有的方式输入一些如网络俚语、游戏术语、部分花名等，以区别于正常、有意义的词组，这对我来说是个好主意。

再次感谢解答。
