### ISSUE TITLE
“礼乐”编码问题

### ISSUE THREAD

**Issue by qchenac** [pingshunhuangalex/rime-xkjd#6]
很欣赏作者拨乱反正的目标清晰的改进思路，“我流”的使用体验很清爽。一个小问题，礼乐似乎应当是lkyho，而现在的编码是 lkleou
ps: 或许可以开一个共享文档，把陆续发现的编码问题集中及时反馈上去

**Comment by qchenac** [comment]
考虑了一下，也许是因为同手的yh不如 le 的指法方便，所以取 le 也说得通

**Comment by pingshunhuangalex** [comment]
谢谢反馈。

这个肯定是编码错误，我流只会在`读音变化不影响其含义（方言或口语读音）`的时候选择一个更好的键位，不会本末倒置为了键位故意选择错误的读音的。因为键道初期词库是由脚本自动生成的，所以在多音字词上有不少疏漏。

我可以快速修复下这个编码，但是如果需要一个集中反馈编码问题的地方，我个人推荐去[键道的QQ群](https://jq.qq.com/?_wv=1027&k=c1T3vOwc)询问一下（共享文档和网站应该都有），现在群友正好在做大量的审核工作。

我因为精力有限，所以重心不在审核修复词库上，但是会不定期的和官方键道词库进行同步的。谢谢

**Comment by pingshunhuangalex** [comment]
在 93e8d6c5219c971bde1b0636715f1d9fbf09202b 中修复了
